---
deployment:
  tasks:
    #- export DEPLOYPATH=/home/ecologra/public_html/alpha
    #- export DEPLOYPATH=/home/ecologra/alpha.ecolograd.ru
    - export DEPLOYPATH=/home/c/cz54834/public_html
    - export REPOPATH=/home/c/cz54834/ecolograd
    - /bin/rm -rf ${DEPLOYPATH}/*
    - /bin/cp -r ${REPOPATH}/public/* $DEPLOYPATH
