baseURL = "/"
languageCode = "ru"
title = "ecolograd.ru"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = "ecolograd"

[menu]

[[menu.main]]
name = "Продукция"
URL = "products"
weight = 1

[[menu.main]]
name = "Статьи"
URL = "blog"
weight = 2

[[menu.main]]
name = "Вопрос-ответ"
URL = "faq"
weight = 3

[[menu.main]]
name = "Контакты"
URL = "contact"
weight = 4

[[menu.footer]]
name = "Продукция"
URL = "products"
weight = 1

[[menu.footer]]
name = "Статьи"
URL = "blog"
weight = 2

[[menu.footer]]
name = "Вопрос-ответ"
URL = "faq"
weight = 3

[[menu.footer]]
name = "Реквизиты"
URL = "requisites"
weight = 4

[[menu.footer]]
name = "Контакты"
URL = "contact"
weight = 5

[params]
mobile = "+7 812 385 81 83"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
copyright = "| Copyright &copy; 2021 [AlfaPlast LLC](https://ecologard.ru) All Rights Reserved | Design [@edyatl](https://github.com/edyatl) |"
mapLatitude = "59.721453312121554"
googleAnalitycsID = ""
currencySymbol = "₽"
author = "@edyatl"
logo = "images/logo.png"
mapLongitude = "30.428555980500033"
location = "Санкт-Петербург, г. Пушкин, Новодеревенская улица, дом 4, литер А, помещение 2-Н, офис 1"
mapMarker = "images/marker.png"
email = "info@ecolograd.ru"
description = "Переработка полимерных материалов"
home = "Главная"

[params.contact]
formAction = "https://9e92775e64940a.localhost.run/feedback/create"

[params.plugins]

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

[[params.social]]
icon = "ti-youtube"
link = "#"

[[params.social]]
icon = "ti-instagram"
link = "#"

[[params.social]]
icon = "fab fa-vk"
link = "#"

[params.preloader]
enable = true
preloader = ""

[params.rating]
enable = true
websiteID = "444334"
publicKey = "811cf0927332bf51f2e12f84608594ac"