backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Добавление и редактирование в разделе Статьи.
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{fname}}" # Name of post file in folder
    fields: # The fields each document in this collection have
      - { label: "File name", name: "fname", widget: "string"  }
      - { label: "Title", name: "title", widget: "string"  }
      - { label: "Publish Date", name: "date", widget: "datetime"  }
      - { label: "Draft", name: "draft", widget: "boolean", default: false  }
      - { label: "Description", name: "description", widget: "text"  }
      - { label: "Photo", name: "image", widget: "image"  }
      - { label: "Author", name: "author", widget: "string"  }
      - { label: "Body", name: "body", widget: "markdown"  }
  - name: "products" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Products" # Used in the UI, ie.: "New Post"
    label_singular: "Product" # Used in the UI, ie: "New Post"
    description: >
      Добавление и редактирование в разделе Продукция.
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{fname}}" # Name of post file in folder
    fields: # The fields each document in this collection have
      - { label: "File name", name: "fname", widget: "string"  }
      - { label: "Title", name: "title", widget: "string"  }
      - { label: "Publish Date", name: "date", widget: "datetime"  }
      - { label: "Draft", name: "draft", widget: "boolean", default: false  }
      - { label: "Description", name: "description", widget: "text"  }
      - { label: "Price", name: "price", widget: "string"  }
      - { label: "PriceBefore", name: "priceBefore", widget: "string", required: false  }
      - { label: "ShortDescription", name: "shortDescription", widget: "text"  }
      - { label: "ProductID", name: "productID", widget: "number", value_type: "int"  }
      - { label: "Type", name: "type", widget: "hidden", default: "products"  }
      - label: "Cover Photos"
        name: "images"
        widget: "list"
        fields: 
          - {label: "Image", name: "image", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown"  }
  - name: "faq" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "FAQ" # Used in the UI, ie.: "New Post"
    #label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Добавление и редактирование в разделе Вопрос-Ответ.
    delete: false # Prevent users from deleting documents in this collection
    files: 
      - label: "FAQ Intro"
        name: "faq_indx_pg"
        file: "content/faq/_index.md"
        description: "Title and intro of FAQ"
        fields:
          - { label: "Title", name: "title", widget: "string"  }
          - { label: "Publish Date", name: "date", widget: "datetime"  }
          - { label: "Draft", name: "draft", widget: "boolean", default: false  }
          - { label: "Description", name: "description", widget: "text"  }
          - { label: "Body", name: "body", widget: "markdown"  }
      - label: "FAQ Items"
        name: "faq_data"
        file: "data/faq.yml"
        description: "List of FAQ items"
        fields:
          - label: "FAQ Data"
            name: "faqItem"
            widget: "list"
            fields: 
              - { label: "Question", name: "title", widget: "text"  }
              - { label: "Answer", name: "content", widget: "text"  }
  - name: "contact" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Contact" # Used in the UI, ie.: "New Post"
    #label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Редактирование в разделе Контакты.
    delete: false # Prevent users from deleting documents in this collection
    files: 
      - label: "Conact page title"
        name: "contact_indx_pg"
        file: "content/contact/_index.md"
        description: "Title of Contact page"
        fields:
          - { label: "Title", name: "title", widget: "string"  }
          - { label: "Publish Date", name: "date", widget: "datetime"  }
          - { label: "Draft", name: "draft", widget: "boolean", default: false  }
          - { label: "Description", name: "description", widget: "text"  }
      - label: "Contact settings / Working time"
        name: "contact_data"
        file: "data/contact.yml"
        description: "Contact settings and working time"
        fields:
          - label: "Contact settings"
            name: "contact"
            widget: "list"
            allow_add: false
            fields: 
              - { label: "Enable", name: "enable", widget: "boolean", default: true  }
              - label: "Office"
                name: "office"
                widget: "list"
                fields:
                  - { label: "Office name", name: "title", widget: "string"  }
                  - { label: "Office intro", name: "content", widget: "text"  }
              #- label: "Open"
                #name: "opennigHour"
                #widget: "list" 
                #fields:
                  #- { label: "Intro", name: "title", widget: "string"  }
                  #- label: "Working time"
                    #name: "dayTimeList"
                    #widget: "list" 
                    #fields:
                      #- { label: "Day", name: "dayTime", widget: "string"  }

          - label: "Map widget"
            name: "map"
            widget: "list"
            allow_add: false
            field: { label: "Enable", name: "enable", widget: "boolean", default: true  }
